### Get html index page
GET http://localhost:9999

### panic
GET http://localhost:9999/panic

### Get with param
GET http://localhost:9999/hello?name=test


### GET with path variable
GET http://localhost:9999/hello/person/1234?age=34
Content-Type: application/json

### GET /v1/message group
GET http://localhost:9999/v1/message
Content-Type: application/json

### GET /v1/status group
GET http://localhost:9999/v1/status
Content-Type: application/json

### GET /users
GET http://localhost:9999/users
Content-Type: application/json

### POST /users
POST http://localhost:9999/users
Content-Type: application/json

{
  "name": "wzj",
  "age": 18,
  "description": "say something to you"
}

### Async call
GET http://localhost:9999/async
Content-Type: application/json

### POST /users
POST http://localhost:9999/xml
Content-Type: application/xml

<root>
    <i-gnored>sflsldf</i-gnored>
    <n-ame>wzj</n-ame>
    <a-ge>18</a-ge>
    18,
    <d-esc>say something to you</d-esc>
</root>